### ISSUE TITLE
cpu一直显示12490，无法修改

### ISSUE THREAD

**Issue by tjpikapika** [geekfory/H610M-A-12400-6600xt-AX201-OC-0.8.5-macOS#6]
非常感谢您的efi文件，目前在我电脑上运行良好。但是不知道为何，cpu一直显示12490，且整个config文件里面不存在这个字段。您的revname已经设置为了12400，但是并没有生效。求告知，您的12490是如何设置的？

**Comment by geekfory** [comment]
你好，我的CPU是12400，你显示12490是不是之前用过其它efi呢，重置下nvram试试呢
