### ISSUE TITLE
无线网卡 cnvi ax201 购买链接有么，想买同款，和楼主一样的机器配置

### ISSUE THREAD

**Issue by TQCasey** [geekfory/H610M-A-12400-6600xt-AX201-OC-0.8.5-macOS#8]

**Comment by geekfory** [comment]
某鱼和某宝有，大概50左右
![Snipaste_2024-04-23_21-42-12](https://github.com/geekfory/Hackintosh-EFI-ASUS-H610M-A-12400-6600xt-AX201/assets/52827965/613d0b0b-5b6d-4a80-84d5-66b2bacbda4b)

**Comment by TQCasey** [comment]
具体的链接有么，太多了，或者告诉下淘宝店铺名字也可以，网上实在太多了，黑苹果速度可以达到1000M么

**Comment by geekfory** [comment]
不太方便推荐店铺。东西一样无所谓哪个店铺买的，你看截图得价格 参考买就行。我的用网环境只有300M，没有1000M不知道能不能跑满。但如果你是苹果手机推荐博通免驱网卡。
